### ISSUE TITLE
Mixed feedbacks, ideas

### ISSUE THREAD

**Issue by ViBE-HU** [fmujakitz/thinkpad-thermal#12]
Hey there. Pretty awesome that your plugin is working on my old ThinkPad R61 and can handle thermal settings.

I have some requests if you mind. Please review. First of all I don't see nothing (I'm on Ubuntu 22.04):
![kép](https://user-images.githubusercontent.com/640109/235491987-db8a635c-9245-4642-8144-86f1e0770433.png)

1. Most of these old machines use old technologies (like CCFL) and hard to see the fan status atm. So please let the plugin use the actual theme colours or fine tune and make it much more visible.

2. Please add fan level 0. _(In my usage case: I know most of the old ThinkPads are worn and the cooling system not so efficient but my machine is in perfect condition. It was a backup machine and never been actively used before I bought it from a reseller's stock. It's totally clean and the cooling paste is fresh. I use it for home office and hardly ever need to cool down the T9300 cause it can operate well and no reason to cool it down till it reach 60-65C degree. And sadly most ThinkPads starts very intensely even at level 1. Mine spins up to 2700RPM. Unnecessary and noisy as hell even with totally clean fan. Since it is no way to modify (afaik) the RPM I recommend to add level 0.)_

3. Please add option to modify level thresholds.

4. Please add multilang support. Would be nice to spread the word and I also would like to translate it.

**Comment by fmujakitz** [comment]
Hi, thanks for the feedback.

1. Extension is not setting any color, and it's inheriting colors from gnome panel, as you can see in the stylesheet

2, 3. I've intentionally left out level 0 from the dropdown, because I've set it to 0 and forgot about it a couple of times while building the extension. So... until there is something that can monitor temps and act as safeguard against temp spikes in the extension, it's not going to be there. But for your use case, it might be worthwhile to check out [thinkfan](https://github.com/vmatare/thinkfan) as it allows you to customize the fan behavior, thresholds etc

4. Added it to todos, maybe it happens soon

**Comment by ViBE-HU** [comment]
I'm not a programmer so I thought that the plugin may use some fixed colour codes. But why is it so grey on my system then? I'm using the default Ubuntu dark theme.

Understood. Hope you figure out it soon. Your plugin is the most complete for this task and that's why I'm interested. Thanks.

**Comment by fmujakitz** [comment]
I have absolutely no idea why it's gray on your system. No colors are being set by the extension

**Comment by ViBE-HU** [comment]
@fmujakitz cool. It's perfect now.
![kép](https://github.com/fmujakitz/thinkpad-thermal/assets/640109/d652535c-563b-4198-a3bf-bcebc702e9b0)

**Comment by ViBE-HU** [comment]
Meanwhile i noticed something else. Is this a bug?
![kép](https://github.com/fmujakitz/thinkpad-thermal/assets/640109/c452e23e-3ac8-4b7b-bb70-3a3b142cc8c1)

`sensors` shows these:
```
coretemp-isa-0000
Adapter: ISA adapter
Core 0:       +41.0?C  (high = +105.0?C, crit = +105.0?C)
Core 1:       +30.0?C  (high = +105.0?C, crit = +105.0?C)

BAT0-acpi-0
Adapter: ACPI interface
in0:          11.83 V  

thinkpad-isa-0000
Adapter: ISA adapter
fan1:        2776 RPM
fan2:        2776 RPM
CPU:          +37.0?C  
GPU:          +27.0?C  
temp3:            N/A  
temp4:            N/A  
temp5:        +50.0?C  
temp6:            N/A  
temp7:        +23.0?C  
temp8:            N/A  

acpitz-acpi-0
Adapter: ACPI interface
temp1:        +37.0?C  (crit = +127.0?C)
temp2:        +41.0?C  (crit = +100.0?C)
```

**Comment by ViBE-HU** [comment]
`sensors -A -j` output:
```
{
   "coretemp-isa-0000":{
      "Core 0":{
         "temp2_input": 50.000,
         "temp2_max": 105.000,
         "temp2_crit": 105.000,
         "temp2_crit_alarm": 0.000
      },
      "Core 1":{
         "temp3_input": 48.000,
         "temp3_max": 105.000,
         "temp3_crit": 105.000,
         "temp3_crit_alarm": 0.000
      }
   },
   "BAT0-acpi-0":{
      "in0":{
         "in0_input": 11.834
      }
   },
   "thinkpad-isa-0000":{
      "fan1":{
         "fan1_input": 0.000
      },
      "fan2":{
         "fan2_input": 0.000
      },
      "CPU":{
         "temp1_input": 55.000
      },
      "GPU":{
         "temp2_input": 36.000
      },
      "temp3":{
ERROR: Can't get value of subfeature temp3_input: Can't read

      },
      "temp4":{
ERROR: Can't get value of subfeature temp4_input: Can't read

      },
      "temp5":{
         "temp5_input": 50.000
      },
      "temp6":{
ERROR: Can't get value of subfeature temp6_input: Can't read

      },
      "temp7":{
         "temp7_input": 29.000
      },
      "temp8":{
ERROR: Can't get value of subfeature temp8_input: Can't read

      }
   },
   "acpitz-acpi-0":{
      "temp1":{
         "temp1_input": 55.000,
         "temp1_crit": 127.000
      },
      "temp2":{
         "temp2_input": 50.000,
         "temp2_crit": 100.000
      }
   }
}
```

Seems like the dropdown menu rarely updates the values. That's why the values differs. 0 shown even if the fan is spinning. So I guess the reason why it shows 0 might be related with the update frequency.

**Comment by fmujakitz** [comment]
Values are updated every 5s. Are you seeing values changing in that timeframe?

**Comment by fmujakitz** [comment]
The fix for missing acpitz values is in main, let me know if v16 works for you.

**Comment by ViBE-HU** [comment]
> The fix for missing acpitz values is in main, let me know if v16 works for you.

Perfect. Everything seems to work now. Thanks.
