### ISSUE TITLE
ubuntu 20.04

### ISSUE THREAD

**Issue by patripfr** [fmujakitz/thinkpad-thermal#18]
Hi, thanks for sharing this great tool!
I would love to use it on my thinkpad p1 that is running on ubuntu 20.04. I tried the 3.14.4 version from the gnome extensions website, but this one looks very outdated and misses the fan control capabilites. Is is possible to run the current version on gnome 3.36.8?

**Comment by fmujakitz** [comment]
Not sure tbh, maybe try and see

**Comment by patripfr** [comment]
thanks for the support
