### ISSUE TITLE
converting to fahrenhheit

### ISSUE THREAD

**Issue by bakedbean** [fmujakitz/thinkpad-thermal#20]
I'm interested in showing temps in Fahrenheit. I found in `extension.ts` where the unit is set, however this only seems to change the label.  The actual temps still seem to be in celsius.  I see that there's a `_toFahrenheit` method, but it doesn't appear to be used.  If I can get any pointers or direction on where to implement that helper method, I'd appreciate it!

Thanks for this extension as well, it's really nice.

**Comment by fmujakitz** [comment]
Should be possible now
