### ISSUE TITLE
Shell extension has no effect / not shown in side or top bar

### ISSUE THREAD

**Issue by klubklubla** [fmujakitz/thinkpad-thermal#25]
Hello,

I was very happy to find this extension, thank you for that. It looks great in the screenshots. Unfortunately, I can't seem to make it work. Turning it on has no effect, I can't see any (graphical) hint of it.

I am using fedora 39 with Gnome 45. I am using Dash to panel but there is no difference in turning it off. I can provide more information if you'd like.

**Comment by fmujakitz** [comment]
Sure thing, more info would be great, looking glass and/or journal
