### ISSUE TITLE
Missing Icons / Incorrect Thermals / How to Configure

### ISSUE THREAD

**Issue by Stredoslovak** [fmujakitz/thinkpad-thermal#8]
Hi, I've installed your extension and it seems to have issues regarding the Icons in the tray - they are non existent. Also, I'd like to know how could I disable some information, since I am lacking a dedicated GPU, access to BAT temps, etc.

DEVICE INFO:

- Model: Lenovo ThinkPad T480
- CPU: i5-8350u
- GPU: UHD 620
- OS: Debian 11
- DE: Gnome 3.38.6
- Kernel: 5.10.0-21-amd64

Output of **_cat /proc/acpi/ibm/thermal_**
`temperatures:	52 -128 0 0 0 0 0 0`
Output of **_cat /proc/acpi/ibm/fan_**
`status:		enabled`
`speed:		2868`
`level:		auto`

**Comment by fmujakitz** [comment]
Gnome 3.38 is not supported, as I made it on 42 and did not consider supporting older versions.

Also, there is no configuration dialog so far, as you can see from the todo list.

**Comment by Stredoslovak** [comment]
Thanks for the reply, I did read the ToDo list.
And I know that it's on the ToDo list, but I was asking more like, in which file can I change the displayed and then recompile the plugin.

Regarding gnome issue:
So no planned support in sight?

**Comment by fmujakitz** [comment]
Have a look at `src/extension.ts`

**Comment by Stredoslovak** [comment]
Thanks, will do
