### ISSUE TITLE
Hide GPU temp if no GPU detected

### ISSUE THREAD

**Issue by MobileAZN** [fmujakitz/thinkpad-thermal#9]
Possible to add some logic to just hide the GPU temp if it doesn't detect one (shown as N/A in the below output)?  I have a T480 without a dGPU (just onboard Intel) and no temp reported. 

Output of Sensors:
`[amcnutt@fedora Projects]$ sensors
thinkpad-isa-0000
Adapter: ISA adapter
fan1:        2868 RPM
CPU:          +53.0°C  
GPU:              N/A  
temp3:         +0.0°C  
temp4:         +0.0°C  
temp5:         +0.0°C  
temp6:         +0.0°C  
temp7:         +0.0°C  
temp8:         +0.0°C  

ucsi_source_psy_USBC000:002-isa-0000
Adapter: ISA adapter
in0:           0.00 V  (min =  +0.00 V, max =  +0.00 V)
curr1:         0.00 A  (max =  +0.00 A)

iwlwifi_1-virtual-0
Adapter: Virtual device
temp1:        +34.0°C  

nvme-pci-3d00
Adapter: PCI adapter
Composite:    +29.9°C  (low  = -40.1°C, high = +83.8°C)
                       (crit = +87.8°C)
Sensor 1:     +39.9°C  (low  = -273.1°C, high = +65261.8°C)
Sensor 2:     +29.9°C  (low  = -273.1°C, high = +65261.8°C)

BAT0-acpi-0
Adapter: ACPI interface
in0:          12.69 V  

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +64.0°C  (high = +100.0°C, crit = +100.0°C)
Core 0:        +64.0°C  (high = +100.0°C, crit = +100.0°C)
Core 1:        +60.0°C  (high = +100.0°C, crit = +100.0°C)
Core 2:        +58.0°C  (high = +100.0°C, crit = +100.0°C)
Core 3:        +58.0°C  (high = +100.0°C, crit = +100.0°C)

pch_skylake-virtual-0
Adapter: Virtual device
temp1:        +49.5°C  

ucsi_source_psy_USBC000:001-isa-0000
Adapter: ISA adapter
in0:           5.00 V  (min =  +5.00 V, max = +20.00 V)
curr1:         3.00 A  (max =  +3.50 A)

BAT1-acpi-0
Adapter: ACPI interface
in0:          12.32 V  

acpitz-acpi-0
Adapter: ACPI interface
temp1:        +53.0°C  (crit = +128.0°C)

[amcnutt@fedora Projects]$ 
`

**Comment by fmujakitz** [comment]
Sure, possible, done and in main, pending approval on gnome exts. Let me know if it works for you

**Comment by MobileAZN** [comment]
Works great!  Thanks!

**Comment by MobileAZN** [comment]
@fmujakitz I don't see a link anywhere to send you a few bucks for a beer/coffee/tea.

**Comment by fmujakitz** [comment]
Added it, thanks!
